mixed-port: 64277
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
secret: txttxtxt2sxtxtxtddxtxt1111111
routing-mark: 6666
hosts:

profile:
  store-selected: false
  store-fake-ip: true

dns:
  enable: false
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip # or redir-host (not recommended)
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  nameserver:
    - 223.5.5.5 # default value
    - 119.29.29.29 # default value
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # dns from dhcp
    # - '8.8.8.8#en0'

proxies:
  - name: "8.152.204.196"
    type: ss
    server: 8.152.204.196
    port: 60001
    cipher: chacha20-ietf-poly1305
    password: "O9E3b1/OdxCrLkTmWyTL7w=="

  - name: "8.146.199.62"
    type: ss
    server: 8.146.199.62
    port: 60001
    cipher: chacha20-ietf-poly1305
    password: "O9E3b1/OdxCrLkTmWyTL7w=="

proxy-groups:
  - name: "test"
    type: load-balance
    proxies:
      - 8.152.204.196
      - 8.146.199.62
    url: 'http://www.gstatic.com/generate_204'
    interval: 2400
    strategy: round-robin

rules:
  - DOMAIN-SUFFIX,google.com,test
  - DOMAIN-KEYWORD,google,test
  - DOMAIN,google.com,test
  - GEOIP,CN,test
  - MATCH,test
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - DOMAIN-SUFFIX,ad.com,REJECT
